/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.eurekaapp.view;

import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import pe.egcc.eurekaapp.db.AccesoDB;
import pe.egcc.eurekaapp.util.Mensaje;
import pe.egcc.eurekaapp.util.ReportViewInternal;

/**
 *
 * @author Gustavo Coronel
 */
public class RepoMovimientos extends javax.swing.JInternalFrame {

  /**
   * Creates new form RepoMovimientos
   */
  public RepoMovimientos() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    txtCuenta = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    btnEjecutar1 = new javax.swing.JButton();
    btnEjecutar2 = new javax.swing.JButton();
    panelRepo = new javax.swing.JPanel();

    setClosable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("REPORTE DE MOVIMIENTOS");

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " [ Criterio ] ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(0, 0, 204))); // NOI18N

    jLabel1.setText("Cuenta:");

    btnEjecutar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/run.png"))); // NOI18N
    btnEjecutar1.setText("Ejecutar 1");
    btnEjecutar1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEjecutar1ActionPerformed(evt);
      }
    });

    btnEjecutar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/run.png"))); // NOI18N
    btnEjecutar2.setText("Ejecutar 1");
    btnEjecutar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEjecutar2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnEjecutar1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnEjecutar2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(193, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnEjecutar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnEjecutar2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 0, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panelRepoLayout = new javax.swing.GroupLayout(panelRepo);
    panelRepo.setLayout(panelRepoLayout);
    panelRepoLayout.setHorizontalGroup(
      panelRepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelRepoLayout.setVerticalGroup(
      panelRepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 469, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(panelRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnEjecutar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutar1ActionPerformed
    try {

      // Usando el archivo JRXML y el objeto Connection
      Connection cn = AccesoDB.getConnection();
      // Parámetros
      Map<String,Object> pars = new HashMap<>();
      pars.put("CUENTA", txtCuenta.getText());
      // Preparando el reporte
      String repoFile = "/pe/egcc/eurekaapp/reports/repoMovimientos.jasper";
      InputStream repoIS = Class.class.getResourceAsStream(repoFile);
      JasperReport repoJR = (JasperReport) JRLoader.loadObject(repoIS);
      JasperPrint repoJP = JasperFillManager.fillReport(repoJR, pars, cn);
      // Visualizando el Reporte
      JasperViewer viewer = new JasperViewer(repoJP, false);
      viewer.setTitle("Reporte de Movimientos");
      viewer.setVisible(true);
    } catch (Exception ex) {
      Mensaje.showError(rootPane, ex.getMessage());
    }
  }//GEN-LAST:event_btnEjecutar1ActionPerformed

  private void btnEjecutar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutar2ActionPerformed
    try {

      // Usando el archivo JRXML y el objeto Connection
      Connection cn = AccesoDB.getConnection();
      // Parámetros
      Map<String,Object> pars = new HashMap<>();
      pars.put("CUENTA", txtCuenta.getText());
      // Preparando el reporte
      String repoFile = "/pe/egcc/eurekaapp/reports/repoMovimientos.jasper";
      InputStream repoIS = Class.class.getResourceAsStream(repoFile);
      JasperReport repoJR = (JasperReport) JRLoader.loadObject(repoIS);
      JasperPrint repoJP = JasperFillManager.fillReport(repoJR, pars, cn);
      // Visualizando el Reporte
      ReportViewInternal view = new ReportViewInternal("REPORTE DE MOVIMIENTOS");
      view.setReporte(repoJP);
      view.setMaximizable(false);
      view.setClosable(false);
      panelRepo.removeAll();
      panelRepo.add(view);
      view.setVisible(true);
      view.setMaximum(true);

    } catch (Exception ex) {
      Mensaje.showError(rootPane, ex.getMessage());
    }
  }//GEN-LAST:event_btnEjecutar2ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEjecutar1;
  private javax.swing.JButton btnEjecutar2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel panelRepo;
  private javax.swing.JTextField txtCuenta;
  // End of variables declaration//GEN-END:variables
}
